### PR TITLE
Now prints correct when given printchar

### PR DESCRIPTION
**Pull request by christopher-jensen**

### CODE REVIEW

**Review by laurits-mumberg — DISMISSED** [review]
LGTM! :trollface:

**Review by JacobToftgaardRasmussen — COMMENTED** [review]
I look forward to your new changes

**Review by JacobToftgaardRasmussen — COMMENTED** [review]
Looks goodi too me

**Review by JacobToftgaardRasmussen — DISMISSED** [review]
Looks goodi too me again

**Review by JacobToftgaardRasmussen — APPROVED** [review]
Yayayayay

**Pull request merged**
