### PR TITLE
New g4 file that abuses recursion

### PR DESCRIPTION
**Pull request by laurits-mumberg**
Precedence seems to be working fine :)

### CODE REVIEW

**Review by humleflue — DISMISSED** [review]
LGTM

**Comment by humleflue** [comment]
I'd like this branch to get merged with the master branch instead, not to mix things up!

**Comment by humleflue** [comment]
I'd like this branch to get merged with the master branch instead, to make sure we don't mix things up!

**Comment by laurits-mumberg** [comment]
:trollface:

**Pull request closed without merging**
